# Generated by Django 5.1.1 on 2024-09-23 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_homework_homework_file_delete_homeworkfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='homework_file',
        ),
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='students.lesson'),
        ),
        migrations.CreateModel(
            name='Homework_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_file', models.FileField(blank=True, null=True, upload_to='homeworks')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.homework')),
            ],
        ),
    ]
