# Generated by Django 5.1.1 on 2024-09-23 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_remove_homework_homework_file_alter_homework_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework_file',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.homework'),
        ),
    ]
