# Generated by Django 5.1.1 on 2024-09-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_homework_file_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework_file',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.homework'),
        ),
    ]
